### ISSUE TITLE
Can't get it to work after the refactor

### ISSUE THREAD

**Issue by trygveaa** [amerlyq/vim-focus-autocmd#2]
I tested the new version, ref your comment in amerlyq/urxvt-ext-evolved#1, but thought it was best to create a new issue here, instead of commenting there.

I can't seem to get it to work though. I tried looking at the code, but I don't know how the plugin works or how to debug it, so didn't get very far. Found some things though:

> let g:focau_options.events   = {'\<F25>': "\e[I", '\<F26>': "\e[O"}

These were F24 and F25 in the previous version. Is it correct that they have changed?

I don't use the widgets, but tried to activate them to see if they worked, and got some errors:
 - "g:focau_clipreg" at line 25 of widget.vim should be "g:focau_clipregs".
 - There are missing some 's at lines 28-31 of widget.vim.

However, none of those fix the issue. Do you have any tips for how to find out what's wrong?

**Comment by amerlyq** [comment]
F25/26 -- it ok, because on some systems/terminals escape codes for F24 and S-F12 are equivalent and I didn't want to obstruct standart keys.
You are right, I forgot to test widgets yesterday. Thanks. They fixed now.

It's my bad, that there are no tests, but I had no idea how to test autocmds and focus events anyway:(
I haven't seen how availible testframeworks could do exactly that -- only testing consequences...

To test if it works, I open two terminal and launch vim in one of them with 'number' widget enabled.
Therefore by switching focus between terminals I can affirm events working. Manual labour, heh...

Currently, I changed way events was triggered in mappings, because they had rare but nasty bugs when mapped directly.
But it seems, with new method Focus* autocmd are launched in sandbox (see :h sandbox), therefore saving buffers on FocusLost don't work, however copying registers and toggle interface elements must do. I will check what I can do about this...

**Comment by trygveaa** [comment]
Hm, I still can't get it to work properly.

The clipboard and number widgets seem to work now. The number widget only works when in insert mode though. But triggering other plugins which have registered commands to Focus* doesn't work.

**Comment by amerlyq** [comment]
Alright, I returned old way mappings worked to allow sideeffects and slightly changed them.
It seems, though, in cmdline sideeffects aren't allowed anyway. Please, see updated FAQ.
If you confirm, that in ```nxoi``` all your events work -- then it's maximum possible at current moment.
Reopen issue if there are some troubles yet not fixed.

**Comment by trygveaa** [comment]
Thanks! Now it works very well.
